title: Saurav Maheshkar
email: sauravvmaheshkar@gmail.com
description: >-
  Growth ML Engineer @Weights and Biases | Kaggle 4x Expert
twitter_username: MaheshkarSaurav
github_username: SauravMaheshkar
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name : "Saurav Maheshkar"
  avatar : "/assets/images/bio.jpg"
  bio : "ML Engineer, Open Source Contributor, Writer"
  location : "New Delhi, India"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MaheshkarSaurav"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SauravMaheshkar"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sauravvmaheshkar"
    - label: "LinkedIn"
      icon: "fa fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/sauravmaheshkar/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MaheshkarSaurav"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SauravMaheshkar"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sauravvmaheshkar"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
