title: Saurav Maheshkar
email: sauravvmaheshkar@gmail.com
repository: SauravMaheshkar/sauravmaheshkar.github.io
description: >- 
  Technical Author at Weights and Biases. Budding Deep Learning Researcher
teaser: /assets/images/Teaser.png
twitter_username: MaheshkarSaurav
github_username: SauravMaheshkar
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  toc_levels: 1..2
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "SauravMaheshkar"
  avatar : "/assets/images/profile.png"
  bio    : "Technical Author at Weights and Biases. Budding Deep Learning Researcher"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MaheshkarSaurav"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SauravMaheshkar"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sauravvmaheshkar"
    - label: "Stack Exchange"
      icon: "fab fa-fw fa-stack-exchange"
      url: "https://stackexchange.com/users/18298626/saurav-maheshkar?tab=accounts"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MaheshkarSaurav"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SauravMaheshkar"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sauravvmaheshkar"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      show_date: true
      mathjax: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "utterances"
  utterances:
    theme: "dark-blue" # "github-dark"
    issue_term: "pathname"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

head_scripts:
  - //cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.js